Task 10. Ajax in Rails
VitaliiLazebnyi/qna pull request #30
Opened 2020-10-15 20:15 UTC by VitaliiLazebnyi

2020-10-16 14:29 UTC, IvanShamatov requested changes

2020-10-16 14:29 UTC, IvanShamatov commented on app/models/vote.rb
> +  after_validation :validate_absence
валидации нужно делать все вместе, а не одни после других.

2020-10-16 14:29 UTC, IvanShamatov commented on app/models/vote.rb
> +    errors.add(:base, 'Already exists.') if Vote.exists?(user_id: user_id, answer: answer_id)
как вариант можно создать уникальный составной индекс в базе
[:user_id, :answer_id]
тогда в рамках одного ответа один и тот же пользователь не сможет создать больше одного голоса. Ошибка в этом случае будет кидаться об неуникальности и сохраняться не будет

2020-10-16 14:29 UTC, IvanShamatov commented on app/models/concerns/votable.rb
> +  # has_many :votes
has_many votes ты правильно начал писать. Видимо что-то не получилось
идея в том, что у тебя в момент инклуда модуля должны появиться эти ассоциации в моделях
для этого используется специальный колбек included

```ruby
module Addressable
  extend ActiveSupport::Concern

  included do
    has_many :votes, as: :votable
  end
end
```

2020-10-16 14:29 UTC, IvanShamatov commented on app/models/concerns/votable.rb
> +    Vote.create(user: user, answer: self, value: 1)
идея модулей в том, что ты один и тот же модуль используешь в разных местах, применяя к разным моделям. Например, голосовать можно как за вопрос, так и за ответ, а следовательно у тебя не может быть в модели vote поле answer, иначе тебе для голосвания за вопросы нужно создавать еще одну модель.

По факту тебе правильно использовать полиморфную связь

2020-10-16 14:29 UTC, IvanShamatov commented on config/routes.rb
> +      delete :vote, action: :destroy, controller: 'votes'
хм. очень похоже на рестфульный экшен, зачем тебе пришлось его ручками прописывать?

Как я вижу, ты не реализовал историю голосовования за вопрос.

2020-10-16 14:29 UTC, IvanShamatov commented on db/migrate/20201014185232_votes.rb
> +      t.integer :value, limit: 1
а как (-1) сохранится в одном символе?

2020-10-16 14:29 UTC, IvanShamatov commented on db/migrate/20201015134826_add_votes_index.rb
> +    add_index :votes, %i[user_id answer_id], unique: true
о, индекс ты создал, а почему тогда логику на него не опираешь?

2020-10-16 20:09 UTC, VitaliiLazebnyi commented on db/migrate/20201015134826_add_votes_index.rb
> +    add_index :votes, %i[user_id answer_id], unique: true
потому что внутренние серверные ошибки никому на проде не нужны
собственно мне в дев режиме сообщения что там где-то продублировался какой-то индекс тоже не очень интересны. 
Вот я сделал валидацию с чем-то похожим на человекочитаемую ошибку.

2020-10-17 19:37 UTC, VitaliiLazebnyi commented on db/migrate/20201014185232_votes.rb
> +      t.integer :value, limit: 1
https://www.devroom.io/2009/08/20/once-and-for-all-rails-migrations-integer-limit-option/

2020-10-18 08:21 UTC, IvanShamatov requested changes
Ну все хорошо, думал уже принимать, но спек на модели не нашел. (shared examples про которые мы говорили)
Консерн с контроллерами и роутами тебе не пригодился, потому что ты пошел рестфульным путем и не стал расширять контроллеры доп экшенами. это ок

2020-10-18 08:21 UTC, IvanShamatov commented on app/models/concerns/votable.rb
> +    Vote.create(user: user, votable: self, value: 1)
тут можно использовать ассоциацию
`votes.create(user: user, value: 1)`
ты ведь заинклудил этот модуль в модель (например) Answer, у тебя появилась ассоциация votes

2020-10-18 08:21 UTC, IvanShamatov commented on app/models/concerns/votable.rb
> +    Vote.where(votable: self).sum(:value)
`votes.sum(:value)`

2020-10-18 08:21 UTC, IvanShamatov commented on app/models/vote.rb
> +    errors.add(:base, 'Already exists.') if Vote.exists?(user_id: user_id, votable: votable)
votable.exists?(user_id: user_id) 
нужно проверить, но должно работать.

2020-10-18 08:21 UTC, IvanShamatov commented on config/routes.rb
> +    delete :votes, controller: :votes, action: :destroy
ок, но лучше все же обернуть в ресурс

```ruby
resources :votes, only: :create do
    delete "/", to: 'votes#destroy'
end
```

2020-10-18 08:21 UTC, IvanShamatov commented on app/views/shared/_vote.html.slim
> +    = link_to '+1', api_votes_path(nil, vote: { votable_type: votable.class.to_s, votable_id: votable.id, value: 1 }), data: { votable_type: votable.class.to_s, votable_id: votable.id }, class: "vote
сделай для этого хелперы, строчку очень сложно читать.

2020-10-18 20:12 UTC, IvanShamatov approved these changes

2020-10-18 20:42 UTC, merged